# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170908_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_First_Name', models.CharField(max_length=60)),
                ('Author_Last_Name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_article',
            new_name='Comments_article',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_text',
            new_name='Comments_text',
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_title',
            field=models.CharField(help_text='Enter title', max_length=200),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
        migrations.AddField(
            model_name='author',
            name='Author_Article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='Article_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Author'),
        ),
    ]
